### PR TITLE
Cardo font

### PR DESCRIPTION
**Pull request by sathomas**
Change base font from Bembo to Cardo for licensing considerations

### CODE REVIEW

**Comment by daveliepmann** [comment]
My apologies that I haven't responded sooner. I think we should stick with ETBembo for now, since we currently have permission to use that (not open-source) font and I'd like to be conservative about switching until we have a firm answer from Mr. Tufte and his font collaborators on how they'd like us to move forward.

**Comment by davelab6** [comment]
@daveliepmann let me know if they are open to libre licensing (I recommend the SIL OFL) as I would be happy to include this in the Google Fonts collection and discuss providing any resources to make it happen

**Comment by davelab6** [comment]
@sathomas why not use the Google Fonts API? :)

**Comment by iDGS** [comment]
FWIW, I looked at Google's Cardo, because I was thinking about maybe adapting Tufte-CSS for use with a CMS. I thought some CMS users would "want to" use a bold font on some occasions (I know, I know), and Google's Cardo at least had that—a bold face along with regular and italic.

However, after hacking a local copy of Tufte-CSS on my laptop to use Google's Cardo, and then making direct, side-by-side comparisons of the two fonts, the ETBembo just looks so... Much... BETTER!

So, maybe count this is a vote for getting ETBembo into Google Fonts? 

(I'd also ask for the addition of a third, bold face, except I fear a hailstorm of rocks and bottles ;-)

**Comment by davelab6** [comment]
I emailed the ETBembo designer, not heard back from him on a price just yet...

**Comment by ghost** [comment]
I'm using Cardo for now. I almost prefer it over ETBembo.

**Comment by gimesi** [comment]
Just tested a Tufte template over on Sharelatex.com. In the source code I found following remarks:

```
% If they're installed, use Bergamo and Chantilly from www.fontsite.com.
% They're clones of Bembo and Gill Sans, respectively.
```

At least Bergamo is available for zero bucks, but I didn't find any info on licensing though...

**Comment by adamschwartz** [comment]
Hey all, I’m happy to let you know that ET has decided to make ETBembo free and open-source. It will soon be in its own repo under @edwardtufte and will have a bower package. It will be removed from https://github.com/edwardtufte/presenter and presenter will bring it in as a bower dependency, which this and other projects will be free to do as well. I’ll let you know when this done.

**Comment by vyp** [comment]
@adamschwartz Awesome! :sparkles: Thank you everyone who made this possible and of course thank you Mr. Tufte.

**Comment by adamschwartz** [comment]
Here’s the repo: https://github.com/edwardtufte/et-bembo. Bower will come a little later. Thanks y’all for your patience.

**Comment by davelab6** [comment]
Thanks @adamschwartz for following up on this :) I'll post issues on that project's issue tracker.

**Comment by daveliepmann** [comment]
Since ET Bembo is now open source, I'm going to close this issue. I appreciate the alternative font suggestion. Thanks!

**Pull request closed without merging**
