### PR TITLE
More granular pull request < 600px layout tweaking

### PR DESCRIPTION
**Pull request by clayh53**
Here is part 1 of a more granular pull request back to  your main repository. This fixes some awkwardness in the layout between 400px and 600px of device width.

### CODE REVIEW

**Comment by daveliepmann** [comment]
Thanks, Clay. I had to manually merge it but everything looks good now.

**Comment by clayh53** [comment]
I think I am grokking how this pull request stuff should work. I'll try to go a more standard route in the future if I have any changes.

**Comment by clayh53** [comment]
FYI - finished up a jekyll theme using the tufte-css

https://github.com/clayh53/tufte-jekyll/tree/master

**Comment by daveliepmann** [comment]
That's awesome!

**Pull request merged**
