### PR TITLE
Remove unnecessary scroll bars from inline content

### LINKED ISSUE #67: Unnecessary Horizontal Scroll Bars
On the latest desktop releases of Firefox, Chrome, and Opera - horizontal scroll bars are shown, even when no scrolling is possible.

overflow

This is caused by the use of `overflow-x: scroll;`

I would suggest changing it to `overflow-x: auto;` to ensure that the scroll bars are only displayed when needed.

Ref: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x

### PR DESCRIPTION
**Pull request by edent**
As per https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-x

Fixes #67

### CODE REVIEW

**Comment by frostbitten** [comment]
looks good from here

**Comment by daveliepmann** [comment]
@frostbitten Do you mean the PR looks good or the non-PR'd site looks good?

**Comment by frostbitten** [comment]
The pull request looks good. This is the right way to remove the scrollbars while leaving the ability for them to show if necessary. I could understand forcing the scrollbar on the code block, for stylistic reasons (it alludes to the computer), but not on the table. If the scrollbar is to be left on code, a little padding would be helpful.

**Comment by daveliepmann** [comment]
Merged from command line. Thank you, and sorry for the delay.

**Pull request closed without merging**
