### PR TITLE
Use fancy quotes

### PR DESCRIPTION
**Pull request by moubry**
You’re using them in most places, but there were a few instances of dumb quotes.

As a sidenote, I noticed you’re using single quotes to ‘quote’ text. I had an urge to replace them with “double” quotes, but wasn’t as sure about that change.

### CODE REVIEW

**Comment by daveliepmann** [comment]
I'd like to hear some commentary on this. I honestly hate the effort it requires to use curly quotes, and avoid it in my own writing. If it's a big enough deal for other people, I could be convinced.

**Comment by moubry** [comment]
I’ll close this pull request since there are merge conflicts and I don’t want to make the changes again. At the very least, you should be consistent. There are examples of curly quotes used in the prose as well as straight quotes, and it just annoyed me. You’re right—it’s not really a big deal.

For what it’s worth, OS X has a System Preference for automatically converting straight quotes into curly quotes.

**Comment by moubry** [comment]
screen shot 2015-08-07 at 11 30 34 am

**Comment by moubry** [comment]
I beg you to reconsider:
- http://smartquotesforsmartpeople.com
- http://practicaltypography.com/straight-and-curly-quotes.html

**Comment by daveliepmann** [comment]
The reason I'm not bullish on this is that _it's not relevant to Tufte CSS_. Are smart quotes better typography? It seems likely. Are they part of the Tufte CSS project? Not really, since they are a character, not a CSS element, and removing them in the demo doc doesn't change anything except the bad example I set for kids. 

The other big reason is that I don't use smart quotes in my emacs workflow—for instance, while writing the demo document. So it's incredibly likely that I'll switch out the existing quotes then reintroduce dumb quotes later while working on something else. Like you said, it's better to be consistent.

**Comment by daveliepmann** [comment]
FYI: https://github.com/daveliepmann/tufte-css/commit/4bfa86d66c743d69bd33491ad5501886ca12321f

I'm giving smart quotes a shot. They'll probably stay for as long as they don't horribly garble my workflow.

**Comment by moubry** [comment]
Yay!

**Comment by daveliepmann** [comment]
Emacs workflow fix is on [emacs.stackexchange](http://emacs.stackexchange.com/a/14779/2277).

**Pull request closed without merging**
